---
# Example: Download latest GitHub Actions artifact with Ansible
# Requires: GITHUB_TOKEN environment variable with repo access

- name: Download Phoebus from GitHub Artifacts
  hosts: localhost
  gather_facts: no
  vars:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    github_repo: "infn-epics/phoebus"  # Change to your repo
    workflow_name: "build_latest.yml"
    
  tasks:
    - name: Get latest successful workflow run
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/actions/workflows/{{ workflow_name }}/runs?status=success&per_page=1"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        return_content: yes
      register: workflow_runs

    - name: Get artifacts list from latest run
      uri:
        url: "{{ workflow_runs.json.workflow_runs[0].artifacts_url }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        return_content: yes
      register: artifacts_list

    - name: Find Linux artifact
      set_fact:
        linux_artifact: "{{ artifacts_list.json.artifacts | selectattr('name', 'match', '.*ubuntu.*') | first }}"

    - name: Download artifact (zip format)
      uri:
        url: "{{ linux_artifact.archive_download_url }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        dest: "/tmp/phoebus-artifact.zip"
        status_code: 200
      register: download_result

    - name: Extract artifact
      unarchive:
        src: "/tmp/phoebus-artifact.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Display downloaded files
      find:
        paths: "/tmp/"
        patterns: "*.tar.gz"
      register: phoebus_files

    - debug:
        msg: "Downloaded: {{ phoebus_files.files | map(attribute='path') | list }}"
